// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ScreenTest
void ui_ScreenTest_screen_init(void);
void ui_event_ScreenTest(lv_event_t * e);
extern lv_obj_t * ui_ScreenTest;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelHelloWorld;
extern lv_obj_t * ui_LabelTime;
extern lv_obj_t * ui_Panel2;
void ui_event_SliderHours(lv_event_t * e);
extern lv_obj_t * ui_SliderHours;
extern lv_obj_t * ui_LabelHours;
extern lv_obj_t * ui_Panel3;
void ui_event_SliderMinutes(lv_event_t * e);
extern lv_obj_t * ui_SliderMinutes;
extern lv_obj_t * ui_LabelMinutes;
extern lv_obj_t * ui_Panel4;
void ui_event_SliderSeconds(lv_event_t * e);
extern lv_obj_t * ui_SliderSeconds;
extern lv_obj_t * ui_LabelSeconds;
extern lv_obj_t * ui_Panel5;
void ui_event_SetTime(lv_event_t * e);
extern lv_obj_t * ui_SetTime;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SetTime;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Digital48);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
