// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void event_screen_init(lv_event_t * e);
void event_slider_set_hours(lv_event_t * e);
void event_slider_set_minutes(lv_event_t * e);
void event_slider_set_seconds(lv_event_t * e);
void event_set_time(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
